"""Sphinx configuration, generated by epythet.

Settings come from ``[tool.epythet]`` in pyproject.toml (or ``[metadata]`` in
setup.cfg). Put project-specific overrides below the import; anything defined
here wins over the generated value.
"""

from epythet.sphinx_conf import *  # noqa: F401,F403
